### ISSUE TITLE
Add support for Chunk

### ISSUE THREAD

**Issue by Vest** [jreijn/spring-comparing-template-engines#15]
Hello @jreijn,

What do you think about adding this template to the project?
[Chunk Templates for Java](http://www.x5software.com/chunk/examples/ChunkExample?loc=en_US) - [github repo](https://github.com/tomj74/chunk-templates)

This project is quite alive.

Kind regards,
Vest

**Comment by tomj74** [comment]
I'll try to put together a PR soon.

**Comment by Vest** [comment]
Oh, great. Thanks.

**Comment by Vest** [comment]
Exists in #38 
Can be closed.
