### ISSUE TITLE
Should we use caching, or disable it

### ISSUE THREAD

**Issue by Vest** [jreijn/spring-comparing-template-engines#18]
Hello everyone,

In the commit e090f2b I turned the View caching on. I did this, because some of viewResolvers had it enabled. I think this should affect the benchmark results.
Here I decided to ask the community, whether the caching should be disabled, or not. What do you think about this?

Kind regards,
Vest

**Comment by jreijn** [comment]
I guess you mean caching of the (compiled) templates right? If so then I guess that's fine. If we disable caching we would also test how fast the templates are compiled/interpreted. Not sure what's right for now. Before I disabled them to see how they actually performed.

**Comment by Vest** [comment]
Yes, you are right - compiled templates.
Because I do not know what was the goal of using apache benchmark, if the template engine caches (or should cache) the generated page.

**Comment by jreijn** [comment]
Well, that's a very valid question. I'll give this some further thought and add some feedback later on.

**Comment by Vest** [comment]
Hi Jeroen,

Do you have the answer? I am planning to disable the caching in my PR... when I finish them :)

Kind regards,
Vest

**Comment by jreijn** [comment]
Hi @Vest sorry for the delay! Yes that seems fine by me. In a production environment you will probably have caching enabled, so we might want to make a note of that. I will also spend some time this week to update some dependencies, since we have quite some old dependencies in the project.

**Comment by Vest** [comment]
Can be closed by #38
I did different tests (on my machine). Now the results look better. JSP is the fastest.
