### ISSUE TITLE
Update Benchmark to Jade4J 1.2.3

### ISSUE THREAD

**Issue by chbloemer** [jreijn/spring-comparing-template-engines#21]
Hi, 
today we released Jade4J 1.2.3 with some performance improvements.
https://github.com/neuland/jade4j/releases

Maybe you could update your benchmark with the current version of the template engine.

Thx.
Christoph

**Comment by jreijn** [comment]
Yes I definitely will do so! Thanks a lot.

**Comment by Vest** [comment]
A small update from me. There is an old artifact **1.2.3** on Maven: https://mvnrepository.com/artifact/de.neuland-bfi/spring-jade4j
But the git-version has the version **1.2.5**.
@chbloemer, can you please tell us whether the Maven repository is going to be updated?

Thanks

**Comment by Vest** [comment]
Should be closed with the PR #22.

**Comment by chbloemer** [comment]
@Vest, I just updated spring-jade4j to version 1.2.5, too.

**Comment by Vest** [comment]
Thank you, @chbloemer. I will update my PR soon.

**Comment by jreijn** [comment]
Jade is now on 1.2.5, so closing this issue.
