### ISSUE TITLE
Update the project to Tomcat 8 and Java 8

### ISSUE THREAD

**Issue by Vest** [jreijn/spring-comparing-template-engines#23]
Hello,

I have found out that Tomcat 7 is not popular anymore, and people are slowly moving towards Java 8. What do you think about updating the solution to support Tomcat 8 and drop :) frameworks who do not support it.

Kind regards

**Comment by jreijn** [comment]
Yeah sounds like a good plan. I've looked at a maven tomcat 8 plugin before, but it does not seem to exist yet. I'll take another look at it.

**Comment by Vest** [comment]
Here is the difficulty, I found yesterday: there is no Tomcat 8 plugin in Maven. People suggest to use Cargo, and with Cargo there is no simple way to create an embedded Tomcat server. Many limitations are taken in place. 

I was able to use the embedded solution with the external installer (sounds confusing, yes?) and it works fine. But (as always in this world) all of a sudden few features from Httl and Mustache disappeared. 
I am reviewing this currently, or I will give the solution with Jetty.

**Comment by jreijn** [comment]
Interesting. As an alternative, we might look at using the spring boot embedded Tomcat container. Perhaps moving the project to spring boot could also be considered. Not sure how many of the frameworks already support spring boot and if it's a clear fit in case multiple views are used.

**Comment by Vest** [comment]
Can be closed by #38

**Comment by jreijn** [comment]
Fixed by #38
