### ISSUE TITLE
Falsy demo urls in README

### ISSUE THREAD

**Issue by Gurkenschreck** [jreijn/spring-comparing-template-engines#29]
Hello,
I found that the demo urls in the README are falsy.
It should be e.g http://localhost:8080/jsp instead of http://localhost:8080/spring-comparing-template-engines/jsp. Same for the URLs in the benchmarking section.

Is that correct?
Greez

**Comment by jreijn** [comment]
I think you are right. The change happened intentionally, so I'm not sure why it's gone now. I'll update the docs. Thanks for letting me know!
