### ISSUE TITLE
Upgrade HtmlFlow to release 3.5

### ISSUE THREAD

**Issue by fmcarvalho** [jreijn/spring-comparing-template-engines#57]
We have fixed some issues on latest releases of HtmlFlow that were preventing the use of HtmlFlow in its entire plenitude within spring-comparing-template-engines. The #56 includes the following updates: 

* Fixed a problem where the block html was written two times into the response. Reported by @Vest at https://github.com/jreijn/spring-comparing-template-engines/issues/34#issuecomment-490099263
* Updated the `HtmlFlowIndexView` according to the new behavior of HtmlFlow in version 3.3. (https://github.com/xmlet/HtmlFlow#33-august-2019) where it: ”_disallows the use of chained calls to `dynamic()` due to unexpected cache behaviors._”. Thus we had to replace the inner invocations of `dynamic()` by `of()`.
* Changed the static method `getView()` of `HtmlFlowIndexView` with a static field `view`.
* Added the `threadSafe()` initialization to the previous view to enable safe use on concurrent benchmarks.

**Comment by jreijn** [comment]
Solved in #56. Thanks @fmcarvalho
