### ISSUE TITLE
Thank you 

### ISSUE THREAD

**Issue by JangCool** [jreijn/spring-comparing-template-engines#61]
I could easily test this data. Thank you.

https://github.com/JangCool/spring-comparing-template-engines/blob/master/README.md

**Comment by Vest** [comment]
Hi @JangCool ,

I am glad that you like this project. Don’t you mind if I close your comment?

Thanks,
Vest

**Comment by Vest** [comment]
Can you please do the measurements for all templates?

**Comment by JangCool** [comment]
> Hi @JangCool ,
> 
> I am glad that you like this project. Don’t you mind if I close your comment?
> 
> Thanks,
> Vest

^^ Sorry, I will close it myself.

**Comment by JangCool** [comment]
> Can you please do the measurements for all templates?

I'll try it when I have time.

**Comment by jreijn** [comment]
Thanks for the feedback @JangCool !
