### ISSUE TITLE
URL context path

### ISSUE THREAD

**Issue by eleumik** [jreijn/spring-comparing-template-engines#8]
Hi,
I have read with interest the results of your tests, thanks.

I installed the web app as a war `/template-engines` and noticed that only thymeleaf adds the context path to the script/css URL(s), the others do not.

**Comment by jreijn** [comment]
Thanks I will look into it!

**Comment by Vest** [comment]
Hello @jreijn,

I have created a pull request that should fix this bug.
Could you please review it and test before doing the actual merge?

Thank you for your time.

**Comment by jreijn** [comment]
Has been resolved by resolving #14
